![Imgur](https://i.imgur.com/h4PPC71.png)
#**10-modul. Maʼlumotlarga ishlov berish. Fayllar va maʼlumotlar ombori**

#**10.25. Modul boʻyicha yakuniy amaliy vazifa**

**Amaliyotni bajargach, fayllar bilan ishlash, API va veb sahifalardan ma’lumot olish, SQL soʻrovlarini yozish va ma’lumotlar omboriga ma’lumot saqlash koʻnikmalariga ega boʻlasiz.**

#**Fayldan oʻqish va yozish**

#**1) CSV fayldan maʼlumotlarni o‘qish**
* https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv havolasidagi maʼlumotlarni `df` oʻzgaruvchisiga saqlang!
* `df` dan tasodifiy 10 ta qatorni ekranga chiqaring!

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv"
df = pd.read_csv(url)
df.head(10)

         Date     Country                          Status  AQI Value
0  2022-07-21     Albania                            Good         14
1  2022-07-21     Algeria                        Moderate         65
2  2022-07-21     Andorra                        Moderate         55
3  2022-07-21      Angola  Unhealthy for Sensitive Groups        113
4  2022-07-21   Argentina                        Moderate         63
5  2022-07-21     Armenia                        Moderate         76
6  2022-07-21   Australia                        Moderate         56
7  2022-07-21     Austria                            Good         45
8  2022-07-21  Azerbaijan                            Good         12
9  2022-07-21     Bahrain                       Unhealthy        165

#**2) CSV fayliga yozish**
* Quyidagi maʼlumotlardan dataframe yarating va uni `people_data.csv` fayliga saqlang.
```
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Ivy", "Jack"],
    "Age": [25, 30, 35, 40, 28, 33, 38, 45, 29, 31],
    "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Khiva", "Namangan", "Fergana", "Jizzakh", "Termez"]
}
```
* Quyidagi maʼlumotlardan yana bir dataframe yarating va uni `people_data_2.csv` fayliga saqlang.
```
{
'Name': ['Alice', 'Bob', 'Charlie'],
'Age': [25, 30, 35]
}
```

In [ ]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Ivy", "Jack"],
    "Age": [25, 30, 35, 40, 28, 33, 38, 45, 29, 31],
    "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Khiva", "Namangan", "Fergana", "Jizzakh", "Termez"]
}

df1 = pd.DataFrame(data)
df1.to_csv("people_data.csv", index = False)

data_1 = {
'Name': ['Alice', 'Bob', 'Charlie'],
'Age': [25, 30, 35]
}

df2 = pd.DataFrame(data_1)
df1.to_csv("people_data_2.csv", index = False)

#**3) HDF5 formati bilan ishlash**
* Yuqorida yaratgan dataframeʼlaringizni `people.h5` faylida saqlang.
* `people.h5` faylidagi barcha jadvallarni oʻqing!

In [ ]:
hdf_obj = pd.HDFStore("people.h5")
hdf_obj['df1'] = df1
hdf_obj['df2'] = df2
hdf_obj.close()
data1 = pd.read_hdf("people.h5", key = 'df1')
data2 = pd.read_hdf("people.h5", key = 'df2')
print(data1.head())
data2.head()

      Name  Age       City
0    Alice   25   Tashkent
1      Bob   30  Samarkand
2  Charlie   35    Bukhara
3    David   40    Andijan
4      Eve   28      Nukus

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

#**4) JSON fayllar bilan ishlash**
1. Quyidagi maʼlumotlarni dataframe koʻrinishida oʻqing va uni `data.json` fayliga yozing!
```
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Ivy", "Jack"],
    "Age": [25, 30, 35, 40, 28, 33, 38, 45, 29, 31],
    "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Khiva", "Namangan", "Fergana", "Jizzakh", "Termez"]
}
```

In [ ]:
df3 = pd.DataFrame(data)
df3.to_json("data.json")

#**5) APIʼlar bilan ishlash**
1. Quyida berilgan API 17 mingdan ortiq kriptovalyutalarning dollarga nisbatan narxi haqidagi maʼlumotlarni saqlaydi. Siz esa endi:
  * API orqali barcha maʼlumotlarni yigʻib oling;
  * ularni dataframe koʻrinishida saqlang;
  * maʼlumotlar boshidan 5 ta qatorni ekranga chiqaring;
  * maʼlumotlar ichidan `bitcoin` ni izlab toping!

In [ ]:
import requests
coins_url = "https://api.coingecko.com/api/v3/coins/list"
r = requests.get(coins_url)
df4 = pd.DataFrame(r.json())
df4.head()
df_bitcoin = df4[df4['name'].str.lower() == 'bitcoin' ]
df_bitcoin.head()

           id symbol     name
2105  bitcoin    btc  Bitcoin

#**6) APIʼlar bilan ishlash**
1. Yuqorida berilgan kriptovalyuta maʼlumotlaridan `id` ustunini roʻyxat koʻrinishida saqlang va bu roʻyxatga `coin_ids` deb nom bering.
2. https://api.coingecko.com/api/v3/simple/price?ids={coin_ids}&vs_currencies=usd havolasi orqali kriptovalyutalarning `usd` ga nisbatini oling (birinchi 100 ta maʼlumotni olish yetarli).
3. 2-shartda berilgan link orqali olingan maʼlumotlarni dataframe koʻrinishida saqlang. Bunda uning indeksi va `usd` ustuni boʻlsin. `index` -> kriptovalyutalar nomi, `usd` -> narxi

#**💡Ishora:** linkdagi `{coin_ids}` oʻzgaruvchi sifatida yozilgan. Siz ham 1-shartda saqlagan `coin_ids` oʻzgaruvchingizni shu qismda yozib keting!

In [ ]:
coin_id_list = df4['id'].tolist()[:100]
coin_ids = ",". join(coin_id_list)
price_url = f"https://api.coingecko.com/api/v3/simple/price?ids={coin_ids}&vs_currencies=usd"
r = requests.get(price_url)
df5 = pd.DataFrame(r.json()).T
df5.index.name = "crypto_names"
df5

                                             usd
crypto_names
_                                       0.004439
000-capital                             0.000009
01111010011110000110001001110100-token  0.000020
01112131415161718192021222324252-token  0.000004
01-token                                0.000109
...                                          ...
4tool-ai                                0.000065
-5                                      0.000353
501-token                               0.000004
5bonacci                                0.000411
5ire                                    0.000028

[100 rows x 1 columns]

#**7) Veb sahifadan oʻqish**
1. Pandas yordamida veb sahifadagi jadvalni yuklab oling.
2. Ma’lumotlarni dataframe ko‘rinishida chiqaring.
3. Agar sahifada bir nechta jadval bo‘lsa, eng muhimini tanlang.
4. Ma’lumotni tozalang (bo‘sh qatorlarni olib tashlang, kerakli ustunlarni tanlang).
5. Natijani CSV faylga saqlang.

***Eslatma: manba sifatida oʻzingiz istagan veb sahifani tanlang. Bu vazifada mustaqil izlanishni oʻrganasiz!***

In [ ]:
url = "https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue"
headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}
r = requests.get(url, headers=headers)

# Pass the raw HTML text into pandas
t = pd.read_html(r.text)
df = t[0]

df.columns = df.columns.droplevel(1)
df = df.drop(["Ranks","Profit","State-owned","Ref."], axis = 1)

columns = [ "Name", "Industry", "Revenue (USD/billion)", "Employees", "Headquarters" ]
df.columns = columns

df.to_csv("companies_highest_revenues.csv", index=False)

/tmp/ipykernel_4398/918943672.py:8: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  t = pd.read_html(r.text)

# **Maʼlumotlar ombori bilan ishlash**

#**8) Maʼlumotlar omborini yuklash va ulanish**
1. https://github.com/alishermutalov/praktikum-datasets/blob/praktikum/chinook.db havolasi orqali maʼlumotlar omborini yuklab oling.
2. Yuklab olingan maʼlumotlar omboriga sqlite3 moduli yordamida **ulaning**.

In [ ]:
!wget https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
!unzip "chinook.zip"

--2026-06-17 15:16:50--  https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
Resolving www.sqlitetutorial.net (www.sqlitetutorial.net)... 172.67.172.250, 104.21.30.141, 2606:4700:3037::ac43:acfa, ...
Connecting to www.sqlitetutorial.net (www.sqlitetutorial.net)|172.67.172.250|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 305596 (298K) [application/zip]
Saving to: ‘chinook.zip’

chinook.zip         100%[===================>] 298.43K  --.-KB/s    in 0.01s

2026-06-17 15:16:50 (23.7 MB/s) - ‘chinook.zip’ saved [305596/305596]

Archive:  chinook.zip
  inflating: chinook.db

In [ ]:
import sqlite3 as sql
db = sql.connect("chinook.db")
cursor = db.cursor()

#**9) Maʼlumotlar omboriga soʻrov yuborish**
1. Jadvallar roʻyxatini koʻring. Ularning ichida `albums` jadvali boʻlsa, shu jadvaldagi barcha maʼlumotlarni (qatorlarni) ekranga chiqaring.
2. Qatorlar soni nechta ekanini aniqlab, uni ham ekranga chiqaring.
3.`albums` jadvalining ustunlari haqidagi maʼlumotlarni ekranga chiqaring.

In [ ]:
cursor.execute("SELECT name from sqlite_master WHERE type = 'table'")
cursor.fetchall()

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',)]

In [ ]:
cursor.execute("SELECT COUNT (*) FROM albums")
cursor.fetchone()

(347,)

#**10) SQL to DataFrame**
1. `albums` jadvalini `pandas.DataFrame` ga oʻtkazing!

In [ ]:
query = "SELECT * FROM albums"
df = pd.read_sql(query, db)
df = df.drop("AlbumId", axis = 1)
df

                                                 Title  ArtistId
0                For Those About To Rock We Salute You         1
1                                    Balls to the Wall         2
2                                    Restless and Wild         2
3                                    Let There Be Rock         1
4                                             Big Ones         3
..                                                 ...       ...
342                             Respighi:Pines of Rome       226
343  Schubert: The Late String Quartets & String Qu...       272
344                                Monteverdi: L'Orfeo       273
345                              Mozart: Chamber Music       274
346  Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 2 columns]

#**11)**  `chinook.db` maʼlumotlar omboridan `tracks` jadvalining birinchi 10 ta qatorini ekranga chiqaring

#💡Ishora: LIMIT

In [ ]:
query = "SELECT * FROM tracks LIMIT 10"
df = pd.read_sql(query, db)
df.drop("TrackId", axis = 1, inplace = True)
df

,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,Balls to the Wall,2,2,1,None,342562,5510424,0.99
2,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
3,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
4,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99
5,Put The Finger On You,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",205662,6713451,0.99
6,Let's Get It Up,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",233926,7636561,0.99
7,Inject The Venom,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",210834,6852860,0.99
8,Snowballed,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",203102,6599424,0.99
9,Evil Walks,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",263497,8611245,0.99

#**12)**`tracks` jadvalidan faqat `Name`, `Composer` ustunlarini tanlab oling!

In [ ]:
query = "SELECT Name, Composer FROM tracks"
df = pd.read_sql(query, db)
df

,Name,Composer
0,For Those About To Rock (We Salute You),"Angus Young, Malcolm Young, Brian Johnson"
1,Balls to the Wall,None
2,Fast As a Shark,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho..."
3,Restless and Wild,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D..."
4,Princess of the Dawn,Deaffy & R.A. Smith-Diesel
...,...,...
3498,Pini Di Roma (Pinien Von Rom) \ I Pini Della V...,None
3499,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",Franz Schubert
3500,"L'orfeo, Act 3, Sinfonia (Orchestra)",Claudio Monteverdi
3501,"Quintet for Horn, Violin, 2 Violas, and Cello ...",Wolfgang Amadeus Mozart
3502,Koyaanisqatsi,Philip Glass

#**13) ORDER BY , DISTINCT**
* `tracks` jadvalidagi takrorlanmaydigan `GenreId` qiymatlarini oling.
* `tracks` jadvalidagi treklarni `Milliseconds` ustuni bo‘yicha kamayish tartibida saralang.

#💡Ishora: ORDER BY , DISTINCT

In [ ]:
query = "SELECT DISTINCT GenreId FROM tracks"
cursor.execute(query)
cursor.fetchall()

[(1,),
 (2,),
 (3,),
 (4,),
 (5,),
 (6,),
 (7,),
 (8,),
 (9,),
 (10,),
 (11,),
 (12,),
 (13,),
 (14,),
 (15,),
 (16,),
 (17,),
 (18,),
 (19,),
 (20,),
 (21,),
 (22,),
 (23,),
 (24,),
 (25,)]

In [ ]:
query = "SELECT * FROM tracks ORDER BY Milliseconds DESC"
df = pd.read_sql(query, db)
df.head(10)

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,2820,Occupation / Precipice,227,3,19,None,5286953,1054423946,1.99
1,3224,Through a Looking Glass,229,3,21,None,5088838,1059546140,1.99
2,3244,"Greetings from Earth, Pt. 1",253,3,20,None,2960293,536824558,1.99
3,3242,The Man With Nine Lives,253,3,20,None,2956998,577829804,1.99
4,3227,"Battlestar Galactica, Pt. 2",253,3,20,None,2956081,521387924,1.99
5,3226,"Battlestar Galactica, Pt. 1",253,3,20,None,2952702,541359437,1.99
6,3243,Murder On the Rising Star,253,3,20,None,2935894,551759986,1.99
7,3228,"Battlestar Galactica, Pt. 3",253,3,20,None,2927802,554509033,1.99
8,3248,Take the Celestra,253,3,20,None,2927677,512381289,1.99
9,3239,Fire In Space,253,3,20,None,2926593,536784757,1.99

#**14) Filtering**
 * `invoices` jadvalidan `Total` summasi 10 dan katta bo‘lgan maʼlumotlarni tanlang.

# 💡Ishora: WHERE

In [ ]:
query = "SELECT * FROM invoices WHERE Total>10"
df = pd.read_sql(query, db)
df.head(10)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
1,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86
2,19,40,2009-03-14 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,13.86
3,26,19,2009-04-14 00:00:00,1 Infinite Loop,Cupertino,CA,USA,95014,13.86
4,33,57,2009-05-15 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,13.86
5,40,36,2009-06-15 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,13.86
6,47,15,2009-07-16 00:00:00,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,13.86
7,54,53,2009-08-16 00:00:00,113 Lupus St,London,None,United Kingdom,SW1V 3EN,13.86
8,61,32,2009-09-16 00:00:00,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,13.86
9,68,11,2009-10-17 00:00:00,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,13.86

#**15) CREATE and INSERT**
* `chinook.db` maʼlumotlar omboriga `users` jadvali yarating. Jadval maydonlari (ustunlar):
  * `id`
  * `name`
  * `birth_date`
* Yaratilgan `users` jadvaliga quyidagi maʼlumotlarni qoʻshing:

    * ```
    [
    ('Alice', 25), ('Bob', 30), ('Charlie', 35), ('David', 28), ('Eve', 22),
    ('Frank', 40), ('Grace', 27), ('Hannah', 32), ('Ivy', 29), ('Jack', 31),
    ('Kevin', 33), ('Liam', 26), ('Mia', 24), ('Noah', 36), ('Olivia', 23),
    ('Peter', 39), ('Quinn', 37), ('Rachel', 34), ('Samuel', 41), ('Tina', 21)
]
 ```

#💡Ishora: CREATE TABLE, INSERT

In [ ]:

cursor.execute(""" CREATE TABLE IF NOT EXISTS users
(name TEXT,
birth_date INT)""")
db.commit()

query = """INSERT INTO users VALUES ('Alice', 25), ('Bob', 30), ('Charlie', 35), ('David', 28), ('Eve', 22), ('Frank', 40), ('Grace', 27), ('Hannah', 32), ('Ivy', 29), ('Jack', 31), ('Kevin', 33), ('Liam', 26), ('Mia', 24), ('Noah', 36), ('Olivia', 23), ('Peter', 39), ('Quinn', 37), ('Rachel', 34), ('Samuel', 41), ('Tina', 21) """
cursor.execute(query)
db.commit()

#**16) UPDATE and DELETE**
* `users` jadvalidagi Alice ismli foydalanuvchining yoshini yangilang.
* `users` jadvalidan Alice ismli foydalanuvchini o‘chiring.

In [ ]:
query ="SELECT birth_date FROM users WHERE name= 'Alice' "
cursor.execute(query)
cursor.fetchall()

[(25,)]

#**17) f-string yordamida SQL komandalarini yozish**
* `customers` jadvalidan `FirstName` va `LastName` bo‘yicha qidiruv qiladigan f-string yozing.

In [ ]:
first_name = input("Please, write the first name: ")
last_name = input("Please, write the last name: ")


query = f"SELECT * FROM customers WHERE FirstName = '{first_name}' AND LastName = '{last_name}'"
df = pd.read_sql(query, db)
df

Please, write the first name: Tim
Please, write the last name: Goyer

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3

#**18)  AND and OR operators**

* `invoices` jadvalidan `BillingCountry` Germaniya yoki Fransiya boʻlgan va `Total` summasi 5 dan katta bo‘lgan kerakli qatorlarni tanlang.

#💡Ishora: AND, OR

In [ ]:
query = "SELECT * FROM invoices WHERE (BillingCountry = 'Germany' OR BillingCountry = 'France') AND Total> 5"
df = pd.read_sql(query, db)
df

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86
1,19,40,2009-03-14 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,13.86
2,31,42,2009-05-07 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,5.94
3,40,36,2009-06-15 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,13.86
4,52,38,2009-08-08 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,5.94
5,67,2,2009-10-12 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,8.91
6,74,40,2009-11-12 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,8.91
7,95,36,2010-02-13 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,8.91
8,117,41,2010-05-22 00:00:00,"11, Place Bellecour",Lyon,None,France,69002,13.86
9,129,43,2010-07-15 00:00:00,"68, Rue Jouvence",Dijon,None,France,21000,5.94
10,138,37,2010-08-23 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,13.86
11,150,39,2010-10-16 00:00:00,"4, Rue Milton",Paris,None,France,75009,5.94
12,172,41,2011-01-20 00:00:00,"11, Place Bellecour",Lyon,None,France,69002,8.91
13,193,37,2011-04-23 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,14.91
14,215,42,2011-07-30 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,13.86
15,236,38,2011-10-31 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,13.86
16,241,2,2011-11-23 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,5.94
17,248,40,2011-12-24 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,5.94
18,269,36,2012-03-26 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,5.94
19,270,42,2012-03-29 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,8.91
20,291,38,2012-06-30 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,8.91
21,313,43,2012-10-06 00:00:00,"68, Rue Jouvence",Dijon,None,France,21000,16.86
22,334,39,2013-01-07 00:00:00,"4, Rue Milton",Paris,None,France,75009,13.86
23,346,41,2013-03-02 00:00:00,"11, Place Bellecour",Lyon,None,France,69002,5.94
24,367,37,2013-06-03 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,5.94
25,368,43,2013-06-06 00:00:00,"68, Rue Jouvence",Dijon,None,France,21000,8.91
26,389,39,2013-09-07 00:00:00,"4, Rue Milton",Paris,None,France,75009,8.91

#**19) BETWEEN and LIKE**

* `invoices` jadvalidan `Total` summasi 5 dan 15 gacha bo‘lgan qatorlarni tanlang.
* `customers` jadvalidan ismi `A` harfi bilan boshlanadigan foydalanuvchilarni tanlang.

In [ ]:
query = "SELECT * FROM invoices WHERE (BillingCountry = 'Germany' OR BillingCountry = 'France') AND Total> 5"
df = pd.read_sql(query, db)
df

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86
1,19,40,2009-03-14 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,13.86
2,31,42,2009-05-07 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,5.94
3,40,36,2009-06-15 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,13.86
4,52,38,2009-08-08 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,5.94
5,67,2,2009-10-12 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,8.91
6,74,40,2009-11-12 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,8.91
7,95,36,2010-02-13 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,8.91
8,117,41,2010-05-22 00:00:00,"11, Place Bellecour",Lyon,None,France,69002,13.86
9,129,43,2010-07-15 00:00:00,"68, Rue Jouvence",Dijon,None,France,21000,5.94
10,138,37,2010-08-23 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,13.86
11,150,39,2010-10-16 00:00:00,"4, Rue Milton",Paris,None,France,75009,5.94
12,172,41,2011-01-20 00:00:00,"11, Place Bellecour",Lyon,None,France,69002,8.91
13,193,37,2011-04-23 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,14.91
14,215,42,2011-07-30 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,13.86
15,236,38,2011-10-31 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,13.86
16,241,2,2011-11-23 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,5.94
17,248,40,2011-12-24 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,5.94
18,269,36,2012-03-26 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,5.94
19,270,42,2012-03-29 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,8.91
20,291,38,2012-06-30 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,8.91
21,313,43,2012-10-06 00:00:00,"68, Rue Jouvence",Dijon,None,France,21000,16.86
22,334,39,2013-01-07 00:00:00,"4, Rue Milton",Paris,None,France,75009,13.86
23,346,41,2013-03-02 00:00:00,"11, Place Bellecour",Lyon,None,France,69002,5.94
24,367,37,2013-06-03 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,5.94
25,368,43,2013-06-06 00:00:00,"68, Rue Jouvence",Dijon,None,France,21000,8.91
26,389,39,2013-09-07 00:00:00,"4, Rue Milton",Paris,None,France,75009,8.91

#**20) DataFrame to SQL**
* Quyidagi maʼlumotlardan dataframe yarating.
  ```
  sales_data = {
    "sale_id": list(range(1, 21)),  # 1 dan 20 gacha boʻlgan unikal IDʼlar
    "product_name": [
        "Laptop", "Smartphone", "Tablet", "Headphones", "Smartwatch",
        "Monitor", "Keyboard", "Mouse", "Printer", "Camera",
        "Speaker", "Game Console", "TV", "Router", "Power Bank",
        "Hard Drive", "USB Flash", "Graphics Card", "Microphone", "VR Headset"
    ],
    "quantity": [2, 5, 3, 10, 4, 6, 8, 12, 3, 5, 7, 9, 4, 2, 11, 6, 15, 1, 3, 2],
    "price": [1200, 800, 450, 200, 300, 500, 100, 50, 250, 700,
              150, 400, 1000, 90, 60, 110, 30, 1500, 80, 600],
    "sale_date": [
        "2025-03-01", "2025-03-02", "2025-03-03", "2025-03-04", "2025-03-05",
        "2025-03-06", "2025-03-07", "2025-03-08", "2025-03-09", "2025-03-10",
        "2025-03-11", "2025-03-12", "2025-03-13", "2025-03-14", "2025-03-15",
        "2025-03-16", "2025-03-17", "2025-03-18", "2025-03-19", "2025-03-20"
    ]
}
```
*Yuqoridagi maʼlumotlar asosida yaratgan dataframeʼingizdan SQL jadvali tuzing va uni `sales` deb nomlang.

In [ ]:
sales_data = {
  "sale_id": list(range(1, 21)),  # 1 dan 20 gacha boʻlgan unikal IDʼlar
  "product_name": [
      "Laptop", "Smartphone", "Tablet", "Headphones", "Smartwatch",
      "Monitor", "Keyboard", "Mouse", "Printer", "Camera",
      "Speaker", "Game Console", "TV", "Router", "Power Bank",
      "Hard Drive", "USB Flash", "Graphics Card", "Microphone", "VR Headset"
  ],
  "quantity": [2, 5, 3, 10, 4, 6, 8, 12, 3, 5, 7, 9, 4, 2, 11, 6, 15, 1, 3, 2],
  "price": [1200, 800, 450, 200, 300, 500, 100, 50, 250, 700,
            150, 400, 1000, 90, 60, 110, 30, 1500, 80, 600],
  "sale_date": [
      "2025-03-01", "2025-03-02", "2025-03-03", "2025-03-04", "2025-03-05",
      "2025-03-06", "2025-03-07", "2025-03-08", "2025-03-09", "2025-03-10",
      "2025-03-11", "2025-03-12", "2025-03-13", "2025-03-14", "2025-03-15",
      "2025-03-16", "2025-03-17", "2025-03-18", "2025-03-19", "2025-03-20"
  ]
}
sales_df = pd.DataFrame(sales_data)
df.to_sql('sales', db, index=False)

27