# ![Imgur](https://i.imgur.com/5pXzCIu.png)

# **DATA SCIENCE VA SUN'IY INTELLEKT PRAKTIKUM**

## Ma'lumotlar tahlili. Pandas kutubxonasi.

# **AMALIYOT**
## DataFrame

### **1-mashq**. `Pandas` kutubxonasini `pd`, `numpy` kutubxonasini `np` deb chaqirib oling

In [ ]:
# Javobni shuyerga yozing
import numpy as np
import pandas as pd

In [ ]:
#@title **To'g'ri javob**
import pandas as pd
import numpy as np

### **2-mashq.** Quyida ko'rsatilgan dataframeni yarating va `df` deb nomlang

In [ ]:
# Javobni shuyerga yozing
viloyatlar = [
    "Andijon viloyati",
    "Buxoro viloyati",
    "Fargona viloyati",
    "Jizzax viloyati",
    "Xorazm viloyati",
    "Namangan viloyati",
    "Navoiy viloyati",
    "Qashqadaryo viloyati",
    "Qoraqalpogʻiston Respublikasi",
    "Samarqand viloyati",
    "Sirdaryo viloyati",
    "Surxondaryo viloyati",
    "Toshkent viloyati",
]
markazlar = [
    "Andijon shahri",
    "Buxoro shahri",
    "Fargona shahri",
    "Jizzax shahri",
    "Urganch shahri",
    "Namangan shahri",
    "Navoiy shahri",
    "Qarshi shahri",
    "Nukus shahri",
    "Samarqand shahri",
    "Guliston shahri",
    "Termiz shahri",
    "Nurafshon shahri",
]
maydonlar = [
    4200,
    39400,
    6800,
    20500,
    6300,
    7900,
    110800,
    28400,
    160000,
    16400,
    5100,
    20800,
    15300,
]
aholi = [
    1899000,
    1384700,
    2597000,
    910500,
    1200000,
    1862000,
    767500,
    2029000,
    1200000,
    2322000,
    648100,
    1676000,
    4450000,
]
data = {
    'Hudud': viloyatlar,
    'Markaz': markazlar,
    'Maydoni':maydonlar,
    'Aholisi': aholi
}
df = pd.DataFrame(data)
print(df)

                            Hudud            Markaz  Maydoni  Aholisi
0                Andijon viloyati    Andijon shahri     4200  1899000
1                 Buxoro viloyati     Buxoro shahri    39400  1384700
2                Fargona viloyati    Fargona shahri     6800  2597000
3                 Jizzax viloyati     Jizzax shahri    20500   910500
4                 Xorazm viloyati    Urganch shahri     6300  1200000
5               Namangan viloyati   Namangan shahri     7900  1862000
6                 Navoiy viloyati     Navoiy shahri   110800   767500
7            Qashqadaryo viloyati     Qarshi shahri    28400  2029000
8   Qoraqalpogʻiston Respublikasi      Nukus shahri   160000  1200000
9              Samarqand viloyati  Samarqand shahri    16400  2322000
10              Sirdaryo viloyati   Guliston shahri     5100   648100
11           Surxondaryo viloyati     Termiz shahri    20800  1676000
12              Toshkent viloyati  Nurafshon shahri    15300  4450000

In [ ]:
# @title **To'g'ri javob**
viloyatlar = [
    "Andijon viloyati",
    "Buxoro viloyati",
    "Fargona viloyati",
    "Jizzax viloyati",
    "Xorazm viloyati",
    "Namangan viloyati",
    "Navoiy viloyati",
    "Qashqadaryo viloyati",
    "Qoraqalpogʻiston Respublikasi",
    "Samarqand viloyati",
    "Sirdaryo viloyati",
    "Surxondaryo viloyati",
    "Toshkent viloyati",
]
markazlar = [
    "Andijon shahri",
    "Buxoro shahri",
    "Fargona shahri",
    "Jizzax shahri",
    "Urganch shahri",
    "Namangan shahri",
    "Navoiy shahri",
    "Qarshi shahri",
    "Nukus shahri",
    "Samarqand shahri",
    "Guliston shahri",
    "Termiz shahri",
    "Nurafshon shahri",
]
maydonlar = [
    4200,
    39400,
    6800,
    20500,
    6300,
    7900,
    110800,
    28400,
    160000,
    16400,
    5100,
    20800,
    15300,
]
aholi = [
    1899000,
    1384700,
    2597000,
    910500,
    1200000,
    1862000,
    767500,
    2029000,
    1200000,
    2322000,
    648100,
    1676000,
    4450000,
]
data = {
    "Hudud":viloyatlar,
    "Markaz":markazlar,
    "Maydoni":maydonlar,
    "Aholisi":aholi
}
df = pd.DataFrame(data)
df

                            Hudud            Markaz  Maydoni  Aholisi
0                Andijon viloyati    Andijon shahri     4200  1899000
1                 Buxoro viloyati     Buxoro shahri    39400  1384700
2                Fargona viloyati    Fargona shahri     6800  2597000
3                 Jizzax viloyati     Jizzax shahri    20500   910500
4                 Xorazm viloyati    Urganch shahri     6300  1200000
5               Namangan viloyati   Namangan shahri     7900  1862000
6                 Navoiy viloyati     Navoiy shahri   110800   767500
7            Qashqadaryo viloyati     Qarshi shahri    28400  2029000
8   Qoraqalpogʻiston Respublikasi      Nukus shahri   160000  1200000
9              Samarqand viloyati  Samarqand shahri    16400  2322000
10              Sirdaryo viloyati   Guliston shahri     5100   648100
11           Surxondaryo viloyati     Termiz shahri    20800  1676000
12              Toshkent viloyati  Nurafshon shahri    15300  4450000

### **2-mashq.** Yuqoridagi df ning yuqorisidan 5 ta qator chiqaring

In [ ]:
# Javobni shuyerga yozing
df.head()

              Hudud          Markaz  Maydoni  Aholisi
0  Andijon viloyati  Andijon shahri     4200  1899000
1   Buxoro viloyati   Buxoro shahri    39400  1384700
2  Fargona viloyati  Fargona shahri     6800  2597000
3   Jizzax viloyati   Jizzax shahri    20500   910500
4   Xorazm viloyati  Urganch shahri     6300  1200000

In [ ]:
#@title **To'g'ri javob**
df.head()

              Hudud          Markaz  Maydoni  Aholisi
0  Andijon viloyati  Andijon shahri     4200  1899000
1   Buxoro viloyati   Buxoro shahri    39400  1384700
2  Fargona viloyati  Fargona shahri     6800  2597000
3   Jizzax viloyati   Jizzax shahri    20500   910500
4   Xorazm viloyati  Urganch shahri     6300  1200000

### **3-mashq.** Yuqoridagi df dan tasodifiy 3 ta qator chiqaring

In [ ]:
# Javobni shuyerga yozing
df.sample(n = 3)

                   Hudud           Markaz  Maydoni  Aholisi
3        Jizzax viloyati    Jizzax shahri    20500   910500
10     Sirdaryo viloyati  Guliston shahri     5100   648100
7   Qashqadaryo viloyati    Qarshi shahri    28400  2029000

In [ ]:
#@title **To'g'ri javob**
df.sample(3)

                Hudud            Markaz  Maydoni  Aholisi
12  Toshkent viloyati  Nurafshon shahri    15300  4450000
2    Fargona viloyati    Fargona shahri     6800  2597000
5   Namangan viloyati   Namangan shahri     7900  1862000

### **4-mashq.** Yuqoridagi df ning 'Hudud' va 'Aholisi' ustinlarini alohida df ko'rinishida chiqaring

In [ ]:
# Javobni shuyerga yozing
data1 = df[['Hudud','Aholisi']]
df1 = pd.DataFrame(data1)
print(type(df1))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
#@title **To'g'ri javob**
df[['Hudud','Aholisi']]

                            Hudud  Aholisi
0                Andijon viloyati  1899000
1                 Buxoro viloyati  1384700
2                Fargona viloyati  2597000
3                 Jizzax viloyati   910500
4                 Xorazm viloyati  1200000
5               Namangan viloyati  1862000
6                 Navoiy viloyati   767500
7            Qashqadaryo viloyati  2029000
8   Qoraqalpogʻiston Respublikasi  1200000
9              Samarqand viloyati  2322000
10              Sirdaryo viloyati   648100
11           Surxondaryo viloyati  1676000
12              Toshkent viloyati  4450000

### **5-mashq.** Yuqoridagi df ning `Markaz` ustunini Series obyekti ko'rinishida chiqaring

In [ ]:
# Javobni shuyerga yozing
print(type(df['Markaz']))

<class 'pandas.core.series.Series'>

In [ ]:
#@title **To'g'ri javob**
df.Markaz

0       Andijon shahri
1        Buxoro shahri
2       Fargona shahri
3        Jizzax shahri
4       Urganch shahri
5      Namangan shahri
6        Navoiy shahri
7        Qarshi shahri
8         Nukus shahri
9     Samarqand shahri
10     Guliston shahri
11       Termiz shahri
12    Nurafshon shahri
Name: Markaz, dtype: object

### **6-mashq.** Yuqoridagi df dan aholi soni 2 milliondan oshiq bo'lgan hududlarni chiqaring

In [ ]:
# Javobni shuyerga yozing
filter = df[df['Aholisi'] > 2_000_000]
filter['Hudud']

2         Fargona viloyati
7     Qashqadaryo viloyati
9       Samarqand viloyati
12       Toshkent viloyati
Name: Hudud, dtype: object

In [ ]:
#@title **To'g'ri javob**
df[df.Aholisi>2_000_000]

                   Hudud            Markaz  Maydoni  Aholisi
2       Fargona viloyati    Fargona shahri     6800  2597000
7   Qashqadaryo viloyati     Qarshi shahri    28400  2029000
9     Samarqand viloyati  Samarqand shahri    16400  2322000
12     Toshkent viloyati  Nurafshon shahri    15300  4450000

### **7-mashq.** Yuqoridagi df dan maydoni 10000kv.km dan kichik bo'lgan hududlarni chiqaring

In [ ]:
# Javobni shuyerga yozing
filter1 = df[df['Maydoni'] < 10000]
filter1

                Hudud           Markaz  Maydoni  Aholisi
0    Andijon viloyati   Andijon shahri     4200  1899000
2    Fargona viloyati   Fargona shahri     6800  2597000
4     Xorazm viloyati   Urganch shahri     6300  1200000
5   Namangan viloyati  Namangan shahri     7900  1862000
10  Sirdaryo viloyati  Guliston shahri     5100   648100

In [ ]:
#@title **To'g'ri javob**
df[df.Maydoni<10000]

### **8-mashq.** Yuqoridagi df ning birinchi ustunini df ning indeksi sifatida ishlating
Ishora:
1. Yoki df ni qayta yarating
2. Yoki `set_index()` metodidan foydalaning

In [ ]:
# Javobni shuyerga yozing
df.set_index(df.columns[0],inplace = True)
df.head()

         Aholisi
Maydoni
4200     1899000
39400    1384700
6800     2597000
20500     910500
6300     1200000

In [ ]:
#@title **To'g'ri javob**
df.set_index(df.columns[0], inplace=True)
df.head()

Empty DataFrame
Columns: []
Index: [1899000, 1384700, 2597000, 910500, 1200000]

### **9-mashq.** Yuqoridagi df dan, Aholisi 2 milliondan oshiq hududlar orasida Samarqand viloyati bor yoki yo'qligini tekshiring

In [ ]:
# Javobni shuyerga yozing
filter3 = df[df.Aholisi>2_000_000]
'Samarqand' in filter3.index

False

In [ ]:
#@title **To'g'ri javob**
"Samarqand viloyati" in df[df.Aholisi>2_000_000].index

### **10-mashq.**  Yuqoridagi df dan faqatgina Andijon, Farg'ona va Namangan viloyatlarini ajratib ko'rsating

In [ ]:
# Javobni shuyerga yozing
df.loc[['Andijon viloyati','Fargona viloyati','Namangan viloyati']]

KeyError: "None of [Index(['Andijon viloyati', 'Fargona viloyati', 'Namangan viloyati'], dtype='object', name='Aholisi')] are in the [index]"

In [ ]:
#@title **To'g'ri javob**
df.loc[["Andijon viloyati","Fargona viloyati","Namangan viloyati"]]

### **11-mashq.**  Yuqoridagi df dan Samarqanda va Toshkent viloyatlarining aholisi va maydonini alohida df ko'rinishida chiqaring

In [ ]:
# Javobni shuyerga yozing

In [ ]:
#@title **To'g'ri javob**
df.loc[['Toshkent viloyati','Samarqand viloyati'],['Maydoni','Aholisi']]

### **12-mashq.**  Yuqoridagi df dan yangi df_new DataFrame yarating. Yangi dataframega faqatgina aholisi 1.5mln dan kam bo'lgan hududlarni ko'chiring.

In [ ]:
# Javobni shuyerga yozing

In [ ]:
#@title **To'g'ri javob**
df_new = df[df.Aholisi<1_500_000]
df_new

AttributeError: 'DataFrame' object has no attribute 'Aholisi'

### **13-mashq.**  Yangi df qatorlari orasida Navoiy, Namangan va Xorazm viloyatlari borligini tekshiring

In [ ]:
# Javobni shuyerga yozing

In [ ]:
#@title **To'g'ri javob**
pd.Index(['Navoiy viloyati','Namangan viloyati','Xorazm viloyati']).isin(df_new.index)

NameError: name 'df_new' is not defined

### **14-mashq.**  Aholisi 1milliondan ko'p, lekin maydoni 10000kv.km dan kam hududlarni chiqaring

In [ ]:
# Javobni shuyerga yozing

In [ ]:
#@title **To'g'ri javob**
df[(df.Aholisi>1_000_000) & (df.Maydoni<10000)]

### **15-mashq.**  Aholisi 1milliondan kam, lekin maydoni 10000kv.km dan ko'p hududlarni chiqaring

In [ ]:
# Javobni shuyerga yozing

In [ ]:
#@title **To'g'ri javob**
df[(df.Aholisi<1_000_000) & (df.Maydoni>10000)]

### **16-mashq.**  Yuqoridagi df dan `Markaz` ustunini tashlab yuboring

In [ ]:
# Javobni shuyerga yozing

In [ ]:
#@title **To'g'ri javob**
df.drop(['Markaz'], axis=1)

### **17-mashq.**  Yuqoridagi df dan Sirdaryo viloyati aholisini chiqaring

In [ ]:
# Javobni shuyerga yozing

In [ ]:
#@title **To'g'ri javob**
df.at['Sirdaryo viloyati','Aholisi']

### **18-mashq.**  Yuqoridagi df dan Buxoro viloyati maydonini chiqaring

In [ ]:
# Javobni shuyerga yozing

In [ ]:
#@title **To'g'ri javob**
df.at['Buxoro viloyati','Maydoni']

### **19-mashq.**  Yuqoridagi df dan Toshkent viloyati maydoni O'zbekiston Respublikasining necha fozini tashkil qilishini toping

In [ ]:
# Javobni shuyerga yozing

In [ ]:
#@title **To'g'ri javob**
tosh_area = df.at['Toshkent viloyati','Maydoni']
uzb_area = sum(df.Maydoni) # yoki
# uzb_area = df.Maydoni.sum()
print(f"Toshkent viloyati maydoni: {tosh_area} kv.km")
print(f"O'zbekiston Respublikasi maydoni: {uzb_area} kv.km")
print(f"Toshkent viloyati maydoni O'zbekiston respublikasining {round(tosh_area/uzb_area*100)}% ni tashkil qiladi")

### **20-mashq.**  Yuqoridagi df dan Toshkent viloyati aholisi O'zbekiston Respublikasining necha fozini tashkil qilishini toping

In [ ]:
# Javobni shuyerga yozing

In [ ]:
#@title **To'g'ri javob**
tosh_area = df.at['Toshkent viloyati','Aholisi']
uzb_area = sum(df.Aholisi) # yoki
# uzb_area = df.Maydoni.sum()
print(f"Toshkent viloyati aholisi: {tosh_area} kishi")
print(f"O'zbekiston Respublikasi aholisi: {uzb_area} kishi")
print(f"Toshkent viloyati aholisi O'zbekiston respublikasining {round(tosh_area/uzb_area*100)}% ni tashkil qiladi")