![Imgur](https://i.imgur.com/h4PPC71.png)

#Data Sayns va Sunʼiy Intellekt Praktikum

#9.32. Pandas kutubxonasi boʻyicha amaliy vazifa.

Yengillik yaratish maqsadida topshiriqlarni `📌Mavzulashtirilgan`

## `📌Pandas kutubxonasini yuklash`

**1.** Pandas kutubxonasini `pd` nomi ostida yuklang va uni chop eting.

In [ ]:
import pandas as pd

**2.** Versiya va konfiguratsiyani tekshiring.

In [ ]:
print(pd.__version__)

2.2.2

**3.** Pandas kutubxonasida mavjud boʻlgan barcha versiya maʼlumotlarini chop eting.

In [ ]:
pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.13.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.6.122+
Version               : #1 SMP Thu Apr 30 18:17:14 UTC 2026
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : en_US.UTF-8
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 2.0.2
pytz                  : 2025.2
dateutil              : 2.9.0.post0
setuptools            : 75.2.0
pip                   : 24.1.2
Cython                : 3.0.12
pytest                : 8.4.2
hypothesis            : None
sphinx                : 8.2.3
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 6.1.1
html5lib              : 1.1
pymysql               : None
psycopg2              : 2.9.12
jinja2                : 3.1.6
IPython               : 7.34.0
pandas_datareader     : 0.10.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.13.5
bottleneck            : 1.4.2
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2025.3.0
gcsfs                 : 2025.3.0
matplotlib            : 3.10.0
numba                 : 0.60.0
numexpr               : 2.14.1
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : 0.30.0
pyarrow               : 18.1.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.16.3
sqlalchemy            : 2.0.49
tables                : 3.10.2
tabulate              : 0.9.0
xarray                : 2025.12.0
xlrd                  : 2.0.2
zstandard             : 0.25.0
tzdata                : 2026.2
qtpy                  : None
pyqt5                 : None

## `📌DataFrame: Asoslar`

DataFramesʼda maʼlumotlarni tanlash (selecting), saralash (sorting), qoʻshish (adding) va yigʻish (aggregating) uchun bir nechta asosiy mashqlar.

💡Eslatma: NumPy kutubxonasini import qilishni unutmang.
``` python
import numpy as np
```

Quyidagi Python lugʻati (dictionary) `data` va Python roʻyxati (list) `labels` ni koʻrib chiqing.


``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

**4.** Ushbu `lugʻat` (dictionary) yordamida `data` dan `labels` indeksiga ega DataFrame yarating.

In [ ]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**5.** Ushbu DataFrame va uning maʼlumotlari haqidagi asosiy maʼlumotlarning qisqacha mazmunini koʻrsating.

`💡Ishora:` DataFrameʼda chaqirilishi mumkin boʻlgan yagona usul mavjud.

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 700.0+ bytes
None

**6.** DataFrame `df` dastlabki 3 qatorini qaytaring.

In [ ]:
df.head(n = 3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

**7.** DataFrame `df`ʼdan faqat `animal` va `age` ustunlarini tanlang.

In [ ]:
df[['animal', 'age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

**8.** `[3, 4, 8]` va `['animal', 'age']` qatorlaridagi maʼlumotlarni tanlang.

In [ ]:
df1 = df.iloc[[3,4,8]][['animal','age']]
df1

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

**9.** Faqat `visits` soni 3 tadan koʻp boʻlgan qatorlarni tanlang.

In [ ]:
df2 = df[df.visits > 3]
df2

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

10. Yosh yoʻqolgan qatorlarni tanlang, yaʼni `NaN`.

In [ ]:
df[df['age'].isna()]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

**11.** `animal` qatoridagi `cat` va `age` qatoridagi `3` dan kichik boʻlgan umumiy qatorlarni tanlang.

In [ ]:
df[(df.age > 3)&(df.animal == 'cat')]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

**12.** `age` 2 va 4 (shu jumladan) orasidagi qatorlarni tanlang.

In [ ]:
df[(df.age > 2) & (df.age < 4)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
j    dog  3.0       1       no

**13.** `f` qatoridagi yoshni `1,5` ga oʻzgartiring.

In [ ]:
df.loc['f','age'] = 1.5
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**14.** `df` yordamida `visits` qatorining yigʻindisini hisoblang.

In [ ]:
df['visits'].sum()

np.int64(19)

**15.** Har bir `animal` uchun oʻrtacha yoshni `df` da hisoblang.

In [ ]:
df.groupby('animal')['age'].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

**16.** `df` yordamida har bir turdagi `animal` sonini hisoblang.

In [ ]:
df['animal'].value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

**17.** `animal` ustunida, `snake` soʻzini `python` soʻziga oʻzgartiring.

In [ ]:
df['animal'] = df.animal.replace('snake','python')
df

   animal  age  visits priority
a     cat  2.5       1      yes
b     cat  3.0       3      yes
c  python  0.5       2       no
d     dog  NaN       3      yes
e     dog  5.0       2       no
f     cat  1.5       3       no
g  python  4.5       1       no
h     cat  NaN       1      yes
i     dog  7.0       2       no
j     dog  3.0       1       no

## `📌DataFrame: Murakkab`

### Darajasi murakkabroq vazifa: toʻgʻri javob olish uchun ikki yoki undan ortiq usullarni birlashtirish kerak boʻlishi mumkin

Oldingi boʻlim DataFrameʼning asosiy, ammo muhim operatsiyalari boʻyicha vazifalari jamlagan edi. Quyida maʼlumotlarni kesishingiz kerak boʻlgan mashqlar mavjud.

**18.** Sizda butun sonlardan iborat `A` ustunli DataFrame `df` mavjud. Misol uchun:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

Yuqoridagi qator bilan bir xil butun sonni oʻz ichiga olgan qator yarating.


💡Sizda quyidagi qiymatlarni oʻz ichiga olgan ustun paydo boʻlishi kerak:

```python
1, 2, 3, 4, 5, 6, 7
```

In [ ]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
df1 = pd.DataFrame(df['A'].unique())
df1

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7

**19.** Raqamli qiymatlardan iborat DataFrame berildi.

```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # float qiymatlarining 5x3 oʻlchovi
```

Qatordagi har bir elementdan satrning oʻrtacha qiymatini qanday ayirish mumkin?

In [ ]:
df = pd.DataFrame(np.random.random(size=(5, 3))) # float qiymatlarining 5x3 oʻlchovi
df.sub(df.mean(axis = 1), axis = 0)

          0         1         2
0  0.039879  0.148440 -0.188319
1  0.357826  0.051816 -0.409642
2 -0.395656  0.115070  0.280586
3 -0.300863  0.294018  0.006845
4  0.125510 -0.257386  0.131876

**20.** Sizda 10 ta haqiqiy raqamlar ustunidan iborat DataFrame mavjud:

``` python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
Qaysi sonlar ustunining yigʻindisi eng kichik ekanini hisoblang. U ustunning yorligʻini qaytaring.

In [ ]:
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
df_sum = df.sum(axis = 0)
df_sum.idxmin()

'e'

**21.** Quyida butun sonlardan iborat DataFrame `df` mavjud. Har bir satrga  5 ta yozuv `NaN` qiymatlari kiritilgan.

DataFrameʼning har bir qatori uchun uchinchi `NaN` qiymatini oʻz ichiga olgan ustunni toping.

Ustun yorliqlarini qaytarishingiz kerak: `e, c, d, h, d`

In [ ]:
nan = np.nan
data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)

# Javobni bu yerga yozing.
third_nan = df.apply(lambda row: row.index[row.isna()][2],axis = 1)
third_nan

0    e
1    c
2    d
3    h
4    d
dtype: object

**22.** DataFrame `grps` guruhlari ustuniga va `vals` butun qiymatlari ustuniga ega:

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
Har bir `grps` uchun uchta eng katta qiymatning yig‘indisini toping.

💡Javobni quyidagicha yakunlashingiz kerak:
```
grps
a    409
b    156
c    345
```

     'a   a  a b  b  c a a  b  c  c   c  b  b  c'
      12,345,3,1,45,14,4,52,54,23,235,21,57,3,87

In [ ]:
# Javobni bu yerga yozing.
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
df.groupby('grps')['vals'].apply(lambda x: x.nlargest(3).sum())

grps
a    409
b    156
c    345
Name: vals, dtype: int64

**23.** Quyida tuzilgan DataFrame `df` ikkita butun son ustuniga ega `A` va `B`. `A` dagi qiymatlar 1 dan 100 gacha (shu jumladan).

`A` dagi har bir 10 ta ketma-ket butun sonlar guruhi uchun (ya’ni `(0, 10]`, `(10, 20]`, ...) 'B' ustunidagi mos qiymatlar yigʻindisini hisoblang.

Javob quyidagicha boʻlishi kerak:

```
A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
```

In [ ]:
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])
df
# Javobni bu yerga yozing!
bins = []
for n in range (0,91,10) :
  bins.append(n)
print(bins)
df['A_bin'] = pd.cut(df['A'], bins)
df.groupby('A_bin')['B'].sum()

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

/tmp/ipykernel_1581/613940345.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('A_bin')['B'].sum()

A_bin
(0, 10]     635
(10, 20]    360
(20, 30]    315
(30, 40]    306
(40, 50]    750
(50, 60]    284
(60, 70]    424
(70, 80]    526
(80, 90]    835
Name: B, dtype: int64

**24.** 'X' butun son ustuni boʻlgan DataFrame:
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```

Har bir qiymat uchun farqni oldingi nolga qaytaring.

Sizda natija quyidagicha boʻlishi kerak:

```
[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
```

Buni yangi `Y` ustuni deb nomlang.

In [ ]:
#javobni bu yerga yozing!
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
counter = []
count = 0
for num in df['X'] :
  if num == 0:
    count = 0
  else :
    count += 1
  counter.append(count)

counter

[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]

##`📌Maʼlumotlarni tozalash`

Bu har doim sodir boʻladi: kimdir sizga notoʻgʻri tuzilgan satrlar, roʻyxatlar va yetishmayotgan maʼlumotlarni oʻz ichiga olgan maʼlumotlarni beradi. Tahlilni davom ettirish uchun uni qanday tartibga keltirasiz?

**25.** Quyidagi jumboqni tasavvur qilishi uchun ushbu misolni DataFrame sifatida oling:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
```
Tartiblaganingizdan soʻng u quyidagi koʻrinishga ega boʻlishi kerak:

```
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
```

In [ ]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})

df

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

**26.** **FlightNumber** ustunidagi baʼzi qiymatlar yoʻq. Ular `NaN` koʻrinishida yozilgan. Bu raqamlar har bir qatorda 10 ga koʻpayishi kerak, shuning uchun 10055 va 10075 ni qoʻyish kerak. Ushbu yetishmayotgan raqamlarni toʻldirish uchun `df` ni oʻzgartiring va ustunni butun son ustuniga aylantiring.

In [ ]:
df['FlightNumber'] = df['FlightNumber'].interpolate()
df['FlightNumber'] = df['FlightNumber'].astype(int)
df

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10045      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"

**27.** **From\_To** ustunini ikkita alohida ustun koʻrinishida yozing.                                          

Toʻgʻri qiymatlarga ega `temp` deb nomlangan yangi Temporary DataFrame berish uchun har bir satrni pastki chiziq chegarasiga ajrating.                                                                     Ushbu Temporary DataFrame ustunlarini `From` va `To` deb nomlang.

In [ ]:
temp = df['From_To'].str.split('_', expand = True)
temp.columns = ['From', 'To']
temp

       From         To
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn

**28.** Temporary DataFrame `temp` da shahar nomlari betartib yozilgan.
Satrlarning faqat birinchi harfi katta yozilishi kerak.
                                                                         (Masalan, "londON" "London" boʻlishi kerak.)

In [ ]:
temp['From'] = temp['From'].str.capitalize()
temp['To'] = temp['To'].str.capitalize()
temp

       From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London

**29**. `Airline` ustunida aviakompaniya nomlari atrofida qoʻshimcha tinish belgilari va boshqa belgilar paydo boʻlganini koʻrishingiz mumkin. Faqat aviakompaniya nomini qoldiring. Masalan, ''(British Airways. )'' `British Airways` koʻrinishida yozilishi kerak.

In [ ]:
df['Airline'] = df['Airline'].str.replace(r'[^a-zA-z\s]','', regex = True)
df['Airline'].str.strip()
df

            From_To  FlightNumber  RecentDelays           Airline
0      LoNDon_paris         10045      [23, 47]               KLM
1      MAdrid_miLAN         10055            []       Air France
2  londON_StockhOlm         10065  [24, 43, 87]  British Airways
3    Budapest_PaRis         10075          [13]        Air France
4   Brussels_londOn         10085      [67, 32]         Swiss Air

**30.** `df` dan **From_To** ustunini oʻchiring va Temporary DataFrame `temp` ustunini qoʻshing.

In [ ]:
df.drop('From_To', axis = 1, inplace = True)
df['From'] = temp['From']
df['To'] = temp['To']
df

   FlightNumber  RecentDelays           Airline      From         To
0         10045      [23, 47]               KLM    London      Paris
1         10055            []       Air France     Madrid      Milan
2         10065  [24, 43, 87]  British Airways     London  Stockholm
3         10075          [13]        Air France  Budapest      Paris
4         10085      [67, 32]         Swiss Air  Brussels     London

**31**. `RecentDelays` ustunida qiymatlar DataFrameʼga roʻyxat sifatida kiritilgan. Vazifangiz birinchi, har bir ikkinchi qiymatni oʻz ustunida va qolgan qiymatlar ham ustunga mos holda chop etish. Agar N-chi qiymat boʻlmasa, qiymat `NaN` deb nomlanishi kerak.

Roʻyxatlar qatorini `delays` nomli DataFrame ichiga kengaytiring, `delay_1`, `delay_2` va qolgan ustunlarni ham nomlarini oʻzgartiring va `df` dagi keraksiz `RecentDelays` ustunini `delays` bilan almashtiring.

Natija quyidagi koʻrinishda boʻlishi kerak:
```
   FlightNumber          Airline      From         To  delay_1  delay_2  delay_3
0         10045              KLM    London      Paris     23.0     47.0      NaN
1         10055       Air France    Madrid      Milan      NaN      NaN      NaN
2         10065  British Airways    London  Stockholm     24.0     43.0     87.0
3         10075       Air France  Budapest      Paris     13.0      NaN      NaN
4         10085        Swiss Air  Brussels     London     67.0     32.0      NaN
```

In [ ]:
delays = pd.DataFrame(df['RecentDelays'].tolist())
delays.columns = [f'delay_{i+1}' for i in range(delays.shape[1])]
df.drop('RecentDelays', axis = 1, inplace = True)
df = pd.concat([df, delays], axis = 1)
df

,FlightNumber,Airline,From,To,delay_1,delay_2,delay_3
0,10045,KLM,London,Paris,23.0,47.0,NaN
1,10055,Air France,Madrid,Milan,NaN,NaN,NaN
2,10065,British Airways,London,Stockholm,24.0,43.0,87.0
3,10075,Air France,Budapest,Paris,13.0,NaN,NaN
4,10085,Swiss Air,Brussels,London,67.0,32.0,NaN

##`📌Minesweeper`


### Minesweeper tarmogʻida xavfsiz kvadratlar uchun raqamlar yaratamiz.

💡 Agar siz Windowsʼning avvalgi versiyalaridan foydalangan boʻlsangiz, Minesweeper bilan tanishsiz:
- https://en.wikipedia.org/wiki/Minesweeper_(video_game)

Agar siz oʻyin bilan tanish boʻlmasangiz, kvadratchalar toʻplamini tasavvur qiling: bu kvadratlarning baʼzilari mineʼni yashiradi. Agar siz mineʼni bossangiz, darhol yoʻqotasiz. Agar siz xavfsiz kvadratni bossangiz, darhol qoʻshni boʻlgan kvadratchalarda qancha mine borligini koʻrsatadigan raqamni koʻrasiz. Oʻyinning maqsadi toʻrdagi mine boʻlmagan barcha kvadratlarni ochishdir.

Ushbu boʻlimda Minesweeper oʻyini uchun kerakli maʼlumotlarni oʻz ichiga olgan DataFrame yaratamiz: kvadratlarning koordinatalari, kvadratda mine bormi va qoʻshni kvadratlarda topilgan mineʼlar sonini aniqlaymiz.

**32**. Tasavvur qiling, biz Minesweeper oʻyinini 5 dan 4 gacha boʻlgan panjarada oʻynayapmiz, yaʼni.
```
X = 5
Y = 4
```
Boshlash uchun ikkita ustunli DataFrame `df` yarating, bu tarmoq uchun har bir koordinatani oʻz ichiga olgan `'x'` va `'y'`. Yaʼni DataFrame ishga tushishi kerak:
```
    x y
0 0 0
1 0 1
2 0 2
```

In [ ]:
import itertools

coordinates= list(itertools.product(range(5), range(4)))
df = pd.DataFrame(coordinates, columns = ['x', 'y'])
df

    x  y
0   0  0
1   0  1
2   0  2
3   0  3
4   1  0
5   1  1
6   1  2
7   1  3
8   2  0
9   2  1
10  2  2
11  2  3
12  3  0
13  3  1
14  3  2
15  3  3
16  4  0
17  4  1
18  4  2
19  4  3

**33**. Ushbu DataFrame `df` uchun yangi nol (safe) va birliklar (mine) ustunini yarating. Har bir joyda mine sodir boʻlish ehtimoli 0,4 boʻlishi kerak.

In [ ]:
import numpy as np
df['mine'] = np.random.choice([0,1], size = len(df), p=[0.6, 0.4])
df

    x  y  mine
0   0  0     0
1   0  1     0
2   0  2     0
3   0  3     1
4   1  0     0
5   1  1     1
6   1  2     0
7   1  3     0
8   2  0     1
9   2  1     0
10  2  2     0
11  2  3     1
12  3  0     0
13  3  1     1
14  3  2     0
15  3  3     0
16  4  0     0
17  4  1     1
18  4  2     0
19  4  3     0

 **34**. Endi ushbu DataFrame uchun `adjacent` nomli yangi ustun yarating. Ushbu ustunda tarmoqdagi qoʻshni kvadratlarda topilgan mineʼlar soni boʻlishi kerak.

(Masalan, `(0, 0)` koordinatasi uchun yozuv boʻlgan birinchi qator uchun `(0, 1)`, `(1, 0)` va `(1) koordinatalarida qancha mine borligini hisoblang. , 1)`.)

In [ ]:
def hisobla_qushni_minalar(row, dataframe):
    x, y = row['x'], row['y']

    qushnilar = dataframe[
        (dataframe['x'] >= x - 1) & (dataframe['x'] <= x + 1) &
        (dataframe['y'] >= y - 1) & (dataframe['y'] <= y + 1) &
        ~((dataframe['x'] == x) & (dataframe['y'] == y))
    ]

    return qushnilar['mine'].sum()

df['adjacent'] = df.apply(hisobla_qushni_minalar, axis=1, dataframe=df)
df.head()

   x  y  mine  adjacent
0  0  0     0         1
1  0  1     0         1
2  0  2     0         2
3  0  3     1         0
4  1  0     0         2

**35**. Mineʼni oʻz ichiga olgan DataFrame qatorlari uchun `adjacent` ustunidagi qiymatni `NaN` ga oʻzgartiring.

In [ ]:
df.loc[df['mine'] == 1, 'adjacent'] = np.nan
df.head(10)

   x  y  mine  adjacent
0  0  0     0       1.0
1  0  1     0       1.0
2  0  2     0       2.0
3  0  3     1       NaN
4  1  0     0       2.0
5  1  1     1       NaN
6  1  2     0       3.0
7  1  3     0       2.0
8  2  0     1       NaN
9  2  1     0       3.0

**36**. DataFrame-ni `adjacent` mineʼlar sonining panjarasiga aylantiring: ustunlar `x` koordinatasi, qatorlar `y` koordinatasi.

In [ ]:
df.pivot(index = 'x', columns = 'y', values = 'adjacent')

y    0    1    2    3
x
0  1.0  1.0  2.0  NaN
1  2.0  NaN  3.0  2.0
2  NaN  3.0  3.0  NaN
3  3.0  NaN  3.0  1.0
4  2.0  NaN  2.0  0.0

##📌BONUS vazifa

Oʻzingiz javob berishni istagan savolni kiriting va unga javob bering.

In [ ]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)
#point out specific value using .iat
df.iloc[2, 3]

'no'